name: Doc24 autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - patient profile autotests
          - doctor profile autotests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: set Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
#        run: sudo apt get install google-chrome
      - name: Install dependensies
        run: pip install -r requirements.txt
      - name: patient profile autotests
        if: "github.event.inputs.deployment_target == 'patient profile autotests'"
        run: pytest -v tests/test_reg_page.py
      - name: doctor profile autotests
        if: "github.event.inputs.deployment_target == 'doctor profile autotests'"
        run: pytest -v tests/test_reg_page.py
