name: Doc24 autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - patient profile autotests
          - doctor profile autotests

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  download-history:
    # if: false
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: >
          ARTIFACT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/senior-tester/run-tests-demo/actions/artifacts?name=allure-results" 
          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
          &&
          curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/senior-tester/run-tests-demo/actions/artifacts/$ARTIFACT_ID/zip 
          -o artifacts.zip &&
          REPORT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/senior-tester/run-tests-demo/actions/artifacts?name=github-pages" 
          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
          &&
          curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/senior-tester/run-tests-demo/actions/artifacts/$REPORT_ID/zip 
          -o pages.zip

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: set Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
#        run: sudo apt get install google-chrome
      - name: Install dependensies
        run: pip install -r requirements.txt
      - name: patient profile autotests
        if: "github.event.inputs.deployment_target == 'patient profile autotests'"
#        run: pytest -v tests/test_reg_page.py::TestLastNameField --alluredir=allure-results
        run: pytest -v tests/test_reg_page.py --alluredir=allure-results
      - name: doctor profile autotests
        if: "github.event.inputs.deployment_target == 'doctor profile autotests'"
        run: pytest -v tests/test_reg_page_doc.py --alluredir=allure-results
      - name: Store allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    if: always()
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz && sudo tar -zxvf allure-2.25.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.25.0/bin/allure /usr/bin/allure
      - name: Download all workflow run artifacts
        if: always()
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - name: Store generated report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    if: always()
    steps:
      - name: Download all workflow run artifacts
        if: always()
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v1.2.9