name: Doc24 autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - patient profile autotests
          - doctor profile autotests

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: set Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
#        run: sudo apt get install google-chrome
      - name: Install dependensies
        run: pip install -r requirements.txt
      - name: patient profile autotests
        if: "github.event.inputs.deployment_target == 'patient profile autotests'"
        run: pytest -v tests/test_reg_page.py::TestLastNameField --alluredir=allure-results
      - name: doctor profile autotests
        if: "github.event.inputs.deployment_target == 'doctor profile autotests'"
        run: pytest -v tests/test_reg_page.py --alluredir=allure-results
      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz && sudo tar -zxvf allure-2.25.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.25.0/bin/allure /usr/bin/allure
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - run: allure generate -c allure-results -o _site
      - name: Store generated report
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path:
            _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9